# Form implementation generated from reading ui file 'mortalCombat.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class player:
    """
    Player class to store and manage individual player attributes.
    Each player has a name, speed, power, and agility stats.
    """
    
    # Special method: constructor. Automatically called when an object is created from the class
    def __init__ (self, name, speed, power, agility):
        """
        Initialize a new player with the given attributes.
        
        Parameters:
            name (str): The player's name
            speed (str): The player's speed stat
            power (str): The player's power stat
            agility (str): The player's agility stat
        """
        self.player_name = name
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility
        
    def modify_stats(self, speed, power, agility):
        """
        Update the player's stats with new values.
        
        Parameters:
            speed (str): New speed value
            power (str): New power value
            agility (str): New agility value
        """
        self.player_speed = speed
        self.player_power = power
        self.player_agility = agility


class Ui_MainWindow(object):
    """
    Main window UI class for the Mortal Combat player management application.
    Handles the creation and modification of player characters.
    """
    
    def setupUi(self, MainWindow):
        """
        Set up the user interface components and connect signals to slots.
        
        Parameters:
            MainWindow: The main window widget
        """
        # Configure main window properties
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        
        # Create central widget
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Create tab widget for different player management functions
        self.tbMortalCompact = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbMortalCompact.setGeometry(QtCore.QRect(20, 20, 761, 501))
        self.tbMortalCompact.setObjectName("tbMortalCompact")
        
        # ===== CREATE PLAYER TAB =====
        self.tbCreatePlayer = QtWidgets.QWidget()
        self.tbCreatePlayer.setObjectName("tbCreatePlayer")
        
        # Name label
        self.lblName = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblName.setGeometry(QtCore.QRect(130, 50, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        
        # Name input field
        self.txtName = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtName.setGeometry(QtCore.QRect(200, 50, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtName.setFont(font)
        self.txtName.setObjectName("txtName")
        
        # Speed label
        self.lblSpeed = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblSpeed.setGeometry(QtCore.QRect(130, 90, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblSpeed.setFont(font)
        self.lblSpeed.setObjectName("lblSpeed")
        
        # Speed input field
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtSpeed.setGeometry(QtCore.QRect(200, 90, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtSpeed.setFont(font)
        self.txtSpeed.setObjectName("txtSpeed")
        
        # Power label
        self.lblPower = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblPower.setGeometry(QtCore.QRect(130, 130, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblPower.setFont(font)
        self.lblPower.setObjectName("lblPower")
        
        # Power input field
        self.txtPower = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtPower.setGeometry(QtCore.QRect(200, 130, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtPower.setFont(font)
        self.txtPower.setObjectName("txtPower")
        
        # Agility label
        self.lblAgility = QtWidgets.QLabel(parent=self.tbCreatePlayer)
        self.lblAgility.setGeometry(QtCore.QRect(130, 170, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblAgility.setFont(font)
        self.lblAgility.setObjectName("lblAgility")
        
        # Agility input field
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tbCreatePlayer)
        self.txtAgility.setGeometry(QtCore.QRect(200, 170, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtAgility.setFont(font)
        self.txtAgility.setObjectName("txtAgility")
        
        # Create player button
        self.btnCreate = QtWidgets.QPushButton(parent=self.tbCreatePlayer)
        self.btnCreate.setGeometry(QtCore.QRect(400, 260, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnCreate.setFont(font)
        self.btnCreate.setObjectName("btnCreate")
        
        # Add Create Player tab to tab widget
        self.tbMortalCompact.addTab(self.tbCreatePlayer, "")
        
        # ===== MODIFY PLAYER TAB =====
        self.tbModifyPlayer = QtWidgets.QWidget()
        self.tbModifyPlayer.setObjectName("tbModifyPlayer")
        
        # Existing players label
        self.lblExistingPlayers = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblExistingPlayers.setGeometry(QtCore.QRect(340, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblExistingPlayers.setFont(font)
        self.lblExistingPlayers.setObjectName("lblExistingPlayers")
        
        # List widget to display all created players
        self.lstExistingPlayers = QtWidgets.QListWidget(parent=self.tbModifyPlayer)
        self.lstExistingPlayers.setGeometry(QtCore.QRect(250, 120, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstExistingPlayers.setFont(font)
        self.lstExistingPlayers.setObjectName("lstExistingPlayers")
        
        # Current speed label
        self.lblCurrentSpeed = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentSpeed.setGeometry(QtCore.QRect(200, 340, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblCurrentSpeed.setFont(font)
        self.lblCurrentSpeed.setObjectName("lblCurrentSpeed")
        
        # Current speed input field
        self.txtCurrentSpeed = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentSpeed.setGeometry(QtCore.QRect(160, 370, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCurrentSpeed.setFont(font)
        self.txtCurrentSpeed.setObjectName("txtCurrentSpeed")
        
        # Current power label
        self.lblCurrentPower = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentPower.setGeometry(QtCore.QRect(360, 340, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblCurrentPower.setFont(font)
        self.lblCurrentPower.setObjectName("lblCurrentPower")
        
        # Current power input field
        self.txtCurrentPower = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentPower.setGeometry(QtCore.QRect(320, 370, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCurrentPower.setFont(font)
        self.txtCurrentPower.setObjectName("txtCurrentPower")
        
        # Current agility label
        self.lblCurrentAgility = QtWidgets.QLabel(parent=self.tbModifyPlayer)
        self.lblCurrentAgility.setGeometry(QtCore.QRect(500, 340, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblCurrentAgility.setFont(font)
        self.lblCurrentAgility.setObjectName("lblCurrentAgility")
        
        # Current agility input field
        self.txtCurrentAgility = QtWidgets.QLineEdit(parent=self.tbModifyPlayer)
        self.txtCurrentAgility.setGeometry(QtCore.QRect(470, 370, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCurrentAgility.setFont(font)
        self.txtCurrentAgility.setObjectName("txtCurrentAgility")
        
        # Modify player button
        self.btnModify = QtWidgets.QPushButton(parent=self.tbModifyPlayer)
        self.btnModify.setGeometry(QtCore.QRect(320, 410, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnModify.setFont(font)
        self.btnModify.setObjectName("btnModify")
        
        # Add Modify Player tab to tab widget
        self.tbMortalCompact.addTab(self.tbModifyPlayer, "")
        
        # Set central widget and menu/status bars
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Set up UI text and translations
        self.retranslateUi(MainWindow)
        
        # Set default tab to Create Player
        self.tbMortalCompact.setCurrentIndex(0)
        
        # Connect signals and slots
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Dictionary to store all created player objects (key: player name, value: player object)
        self.created_players = {}
        
        # Connect Create button to create_player method
        self.btnCreate.clicked.connect(self.create_player)
        
        # Connect list item selection to display_stats method
        self.lstExistingPlayers.itemClicked.connect(self.display_stats)
        
        # Connect Modify button to modify_player_stats method
        self.btnModify.clicked.connect(self.modify_player_stats)
        
    def modify_player_stats(self):
        """
        Modify the stats of the selected player.
        Updates the player object with new speed, power, and agility values.
        Displays success or error message boxes based on the outcome.
        """
        try:
            # Get the selected player name from the list
            name = self.lstExistingPlayers.currentItem().text()
            
            # Get new stat values from input fields
            speed = self.txtCurrentSpeed.text()
            power = self.txtCurrentPower.text()
            agility = self.txtCurrentAgility.text()
            
            # Validate that all fields have values
            if not speed or not power or not agility:
                # Show error message if any field is empty
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setWindowTitle("Input Error")
                msg.setText("Please fill in all stat fields before modifying.")
                msg.exec()
                return
            
            # Retrieve the player object from the dictionary
            playerobject = self.created_players.get(name)
            
            # Update the player's stats
            playerobject.modify_stats(speed, power, agility)
            
            # Show success message
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setWindowTitle("Success")
            msg.setText(f"Player '{name}' stats updated successfully!")
            msg.setInformativeText(f"Speed: {speed}\nPower: {power}\nAgility: {agility}")
            msg.exec()
            
        except AttributeError:
            # Handle case where no player is selected from the list
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setWindowTitle("Selection Error")
            msg.setText("Please select a player from the list first.")
            msg.exec()
            print("AttributeError: No player selected")
            
        except Exception as e:
            # Handle any other unexpected errors
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setWindowTitle("Error")
            msg.setText("An error occurred while modifying player stats.")
            msg.setInformativeText(str(e))
            msg.exec()
            print(f"Error: {e}")
            print(f"Error type: {type(e)}")
    
    def display_stats(self):
        """
        Display the stats of the selected player in the input fields.
        Called when a player is clicked in the list widget.
        """
        try:
            # Get the selected player name
            name = self.lstExistingPlayers.currentItem().text()
            
            # Retrieve the player object
            player_object = self.created_players.get(name)
            
            # Display current stats in the input fields
            self.txtCurrentSpeed.setText(f"{player_object.player_speed}")
            self.txtCurrentPower.setText(f"{player_object.player_power}") 
            self.txtCurrentAgility.setText(f"{player_object.player_agility}")
            
        except AttributeError:
            # Handle case where no player is selected
            print("AttributeError: No player selected")
            
        except Exception as e:
            # Handle any other unexpected errors
            print(f"Error: {e}")
            print(f"Error type: {type(e)}")
        
    def create_player(self):
        """
        Create a new player with the entered stats and add to the players dictionary.
        Also adds the player name to the list widget for future modification.
        """
        try:
            # Get input values from text fields
            name = self.txtName.text()
            speed = self.txtSpeed.text()
            power = self.txtPower.text()
            agility = self.txtAgility.text()
            
            # Validate that name is not empty
            if not name:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setWindowTitle("Input Error")
                msg.setText("Please enter a player name.")
                msg.exec()
                return
            
            # Check if player name already exists
            if name in self.created_players:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setWindowTitle("Duplicate Player")
                msg.setText(f"Player '{name}' already exists.")
                msg.exec()
                return
            
            # Validate that all stat fields have values
            if not speed or not power or not agility:
                msg = QtWidgets.QMessageBox()
                msg.setIcon(QtWidgets.QMessageBox.Icon.Warning)
                msg.setWindowTitle("Input Error")
                msg.setText("Please fill in all stat fields.")
                msg.exec()
                return
            
            # Create new player object
            player_object = player(name, speed, power, agility)
            
            # Add player to dictionary with name as key
            self.created_players[name] = player_object
            
            # Add player name to the list widget
            self.lstExistingPlayers.addItem(name)
            
            # Clear input fields after successful creation
            self.txtName.clear()
            self.txtSpeed.clear()
            self.txtPower.clear()
            self.txtAgility.clear()
            
            # Show success message
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
            msg.setWindowTitle("Success")
            msg.setText(f"Player '{name}' created successfully!")
            msg.exec()
            
        except Exception as e:
            # Handle any unexpected errors during player creation
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Icon.Critical)
            msg.setWindowTitle("Error")
            msg.setText("An error occurred while creating the player.")
            msg.setInformativeText(str(e))
            msg.exec()
            print(f"Error: {e}")
            print(f"Error type: {type(e)}")

    def retranslateUi(self, MainWindow):
        """
        Set up all UI text and translations for the application.
        
        Parameters:
            MainWindow: The main window widget
        """
        _translate = QtCore.QCoreApplication.translate
        
        # Main window title
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        # Create Player tab labels and button
        self.lblName.setText(_translate("MainWindow", "Enter Name"))
        self.lblSpeed.setText(_translate("MainWindow", "Enter Speed"))
        self.lblPower.setText(_translate("MainWindow", "Enter Power"))
        self.lblAgility.setText(_translate("MainWindow", "Enter Agility"))
        self.btnCreate.setText(_translate("MainWindow", "Create Player"))
        self.tbMortalCompact.setTabText(self.tbMortalCompact.indexOf(self.tbCreatePlayer), 
                                         _translate("MainWindow", "Create Player"))
        
        # Modify Player tab labels and button
        self.lblExistingPlayers.setText(_translate("MainWindow", "Existing Players"))
        self.lblCurrentSpeed.setText(_translate("MainWindow", "Speed"))
        self.lblCurrentPower.setText(_translate("MainWindow", "Power"))
        self.lblCurrentAgility.setText(_translate("MainWindow", "Agility"))
        self.btnModify.setText(_translate("MainWindow", "Modify Player"))
        self.tbMortalCompact.setTabText(self.tbMortalCompact.indexOf(self.tbModifyPlayer), 
                                         _translate("MainWindow", "Modify Player"))


# Main execution block
if __name__ == "__main__":
    import sys
    
    # Create application instance
    app = QtWidgets.QApplication(sys.argv)
    
    # Create main window
    MainWindow = QtWidgets.QMainWindow()
    
    # Create UI instance and set up the window
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    
    # Show the window
    MainWindow.show()
    
    # Execute the application event loop
    sys.exit(app.exec())