# Form implementation generated from reading ui file 'studentApp.ui'
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import pymysql as mdb


class Ui_studentApp(object):
    def setupUi(self, studentApp):
        studentApp.setObjectName("studentApp")
        studentApp.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentApp.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentApp)
        self.centralwidget.setObjectName("centralwidget")
        self.tbStudent = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbStudent.setGeometry(QtCore.QRect(50, 20, 721, 501))
        self.tbStudent.setObjectName("tbStudent")
        self.tbStudentInfo = QtWidgets.QWidget()
        self.tbStudentInfo.setObjectName("tbStudentInfo")
        self.lblStudentID = QtWidgets.QLabel(parent=self.tbStudentInfo)
        self.lblStudentID.setGeometry(QtCore.QRect(220, 80, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentID.setFont(font)
        self.lblStudentID.setObjectName("lblStudentID")
        self.lblStudentName = QtWidgets.QLabel(parent=self.tbStudentInfo)
        self.lblStudentName.setGeometry(QtCore.QRect(220, 110, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentName.setFont(font)
        self.lblStudentName.setObjectName("lblStudentName")
        self.lblStudentScore = QtWidgets.QLabel(parent=self.tbStudentInfo)
        self.lblStudentScore.setGeometry(QtCore.QRect(220, 140, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblStudentScore.setFont(font)
        self.lblStudentScore.setObjectName("lblStudentScore")
        self.txtStudentID = QtWidgets.QLineEdit(parent=self.tbStudentInfo)
        self.txtStudentID.setGeometry(QtCore.QRect(310, 70, 113, 21))
        self.txtStudentID.setObjectName("txtStudentID")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbStudentInfo)
        self.txtName.setGeometry(QtCore.QRect(310, 100, 113, 21))
        self.txtName.setObjectName("txtName")
        self.txtScore = QtWidgets.QLineEdit(parent=self.tbStudentInfo)
        self.txtScore.setGeometry(QtCore.QRect(310, 130, 113, 21))
        self.txtScore.setObjectName("txtScore")
        self.btnDisplayData = QtWidgets.QPushButton(parent=self.tbStudentInfo)
        self.btnDisplayData.setGeometry(QtCore.QRect(210, 220, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnDisplayData.setFont(font)
        self.btnDisplayData.setObjectName("btnDisplayData")
        self.btnInsertData = QtWidgets.QPushButton(parent=self.tbStudentInfo)
        self.btnInsertData.setGeometry(QtCore.QRect(360, 220, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnInsertData.setFont(font)
        self.btnInsertData.setObjectName("btnInsertData")
        self.twStudentData = QtWidgets.QTableWidget(parent=self.tbStudentInfo)
        self.twStudentData.setGeometry(QtCore.QRect(210, 250, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.twStudentData.setFont(font)
        self.twStudentData.setObjectName("twStudentData")
        self.twStudentData.setColumnCount(0)
        self.twStudentData.setRowCount(0)
        self.tbStudent.addTab(self.tbStudentInfo, "")
        self.tbStudentGrade = QtWidgets.QWidget()
        self.tbStudentGrade.setObjectName("tbStudentGrade")
        self.lstStudentData = QtWidgets.QListWidget(parent=self.tbStudentGrade)
        self.lstStudentData.setGeometry(QtCore.QRect(230, 20, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstStudentData.setFont(font)
        self.lstStudentData.setObjectName("lstStudentData")
        self.btnExportData = QtWidgets.QPushButton(parent=self.tbStudentGrade)
        self.btnExportData.setGeometry(QtCore.QRect(300, 250, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnExportData.setFont(font)
        self.btnExportData.setObjectName("btnExportData")
        self.tbStudent.addTab(self.tbStudentGrade, "")
        studentApp.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentApp)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        studentApp.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentApp)
        self.statusbar.setObjectName("statusbar")
        studentApp.setStatusBar(self.statusbar)

        self.retranslateUi(studentApp)
        self.tbStudent.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(studentApp)
        
        # Store reference to main window
        self.main_window = studentApp
        
        # Database connection variable
        self.connection = None
        
        # Connect button click events
        self.btnDisplayData.clicked.connect(self.display_data)
        self.btnInsertData.clicked.connect(self.insert_data)
        self.btnExportData.clicked.connect(self.export_data)
        
        # Connect tab change event
        self.tbStudent.currentChanged.connect(self.tab_changed)
        
        # Initialize application on form load
        self.form_load()

    def retranslateUi(self, studentApp):
        _translate = QtCore.QCoreApplication.translate
        studentApp.setWindowTitle(_translate("studentApp", "Student App"))
        self.lblStudentID.setText(_translate("studentApp", "Student ID"))
        self.lblStudentName.setText(_translate("studentApp", "Name"))
        self.lblStudentScore.setText(_translate("studentApp", "Score"))
        self.btnDisplayData.setText(_translate("studentApp", "Display Data"))
        self.btnInsertData.setText(_translate("studentApp", "Insert Data"))
        self.tbStudent.setTabText(self.tbStudent.indexOf(self.tbStudentInfo), _translate("studentApp", "Student Info"))
        self.btnExportData.setText(_translate("studentApp", "Export Data"))
        self.tbStudent.setTabText(self.tbStudent.indexOf(self.tbStudentGrade), _translate("studentApp", "Student Grade"))
    
    def form_load(self):
        #Form load event: Opens database connection, reads external file, and inserts data into database table
        try:
            # Open database connection
            self.open_connection()
            
            # Read data from external file and insert into database
            self.load_data_from_file()
            
            # Close database connection
            self.close_connection()
            
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Form load error: {str(e)}")
    
    def open_connection(self):
        # Open connection to MySQL database
        try:
            self.connection = mdb.connect(
                host="localhost",
                port=3306,
                database="project4db",
                user="442user",
                password="442user"
            )
        except Exception as e:
            QMessageBox.critical(self.main_window, "Database Error", f"Failed to connect: {str(e)}")
            raise
    
    def close_connection(self):
        #Close database connection
        try:
            if self.connection:
                self.connection.close()
        except Exception as e:
            QMessageBox.warning(self.main_window, "Warning", f"Error closing connection: {str(e)}")
    
    def load_data_from_file(self):
        #Read student data from external file and insert into database table 
        #File format: studentid,studentname,studentscore
        try:
            # Open file in read mode
            file_object = open("studentdata.txt", "r")
            
            # Read all lines from file
            lines = file_object.readlines()
            
            cursor = self.connection.cursor()
            
            # Iterate over each line in the file
            for line in lines:
                # Remove leading and trailing spaces
                line = line.strip()
                
                # Skip empty lines
                if not line:
                    continue
                
                # Split the line by comma
                data = line.split(",")
                
                # Extract student id, name, and score
                student_id = int(data[0].strip())
                student_name = data[1].strip()
                student_score = int(data[2].strip())
                
                # Check if student id already exists
                check_query = "SELECT studentid FROM student_data WHERE studentid = %s"
                cursor.execute(check_query, (student_id,))
                result = cursor.fetchone()
                
                # Insert only if student id doesn't exist
                if not result:
                    insert_query = "INSERT INTO student_data (studentid, studentname, studentscore) VALUES (%s, %s, %s)"
                    cursor.execute(insert_query, (student_id, student_name, student_score))
            
            # Commit changes to database
            self.connection.commit()
            cursor.close()
            file_object.close()
            
        except FileNotFoundError:
            QMessageBox.warning(self.main_window, "File Error", "studentdata.txt file not found")
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Error loading data from file: {str(e)}")
    
    def display_data(self):
        #Display Data button click event
        #Retrieves all student data from database and displays in table widget
        try:
            # Open database connection
            self.open_connection()
            
            cursor = self.connection.cursor()
            
            # Query to select all data from student table
            query = "SELECT studentid, studentname, studentscore FROM student_data"
            cursor.execute(query)
            
            # Fetch all rows
            results = cursor.fetchall()
            
            # Set up table widget
            self.twStudentData.setRowCount(len(results))
            self.twStudentData.setColumnCount(3)
            self.twStudentData.setHorizontalHeaderLabels(["Student ID", "Name", "Score"])
            
            # Populate table widget with data
            for row_index, row_data in enumerate(results):
                for col_index, cell_data in enumerate(row_data):
                    self.twStudentData.setItem(row_index, col_index, 
                                               QtWidgets.QTableWidgetItem(str(cell_data)))
            
            cursor.close()
            self.close_connection()
            
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Error displaying data: {str(e)}")
    
    def insert_data(self):
        #Insert Data button click event
        #Validates input and inserts new student data into database
        try:
            # Get input values from text boxes
            student_id = self.txtStudentID.text().strip()
            student_name = self.txtName.text().strip()
            student_score = self.txtScore.text().strip()
            
            # Validation: Check if all fields are filled
            if not student_id or not student_name or not student_score:
                QMessageBox.warning(self.main_window, "Validation Error", 
                                   "All fields must be filled out")
                return
            
            # Validation: Check if student id is an integer
            try:
                student_id = int(student_id)
            except ValueError:
                QMessageBox.warning(self.main_window, "Validation Error", 
                                   "Student ID must be a valid integer")
                return
            
            # Validation: Check if student score is an integer
            try:
                student_score = int(student_score)
            except ValueError:
                QMessageBox.warning(self.main_window, "Validation Error", 
                                   "Student score must be a valid integer")
                return
            
            # Validation: Check if score is between 0 and 100
            if student_score < 0 or student_score > 100:
                QMessageBox.warning(self.main_window, "Validation Error", 
                                   "Student score must be between 0 and 100")
                return
            
            # Open database connection
            self.open_connection()
            
            cursor = self.connection.cursor()
            
            # Check for duplicate student id
            check_query = "SELECT studentid FROM student_data WHERE studentid = %s"
            cursor.execute(check_query, (student_id,))
            result = cursor.fetchone()
            
            if result:
                QMessageBox.warning(self.main_window, "Duplicate Error", 
                                   f"Student ID {student_id} already exists")
                cursor.close()
                self.close_connection()
                return
            
            # Insert data into database
            insert_query = "INSERT INTO student_data (studentid, studentname, studentscore) VALUES (%s, %s, %s)"
            cursor.execute(insert_query, (student_id, student_name, student_score))
            
            # Commit changes
            self.connection.commit()
            
            cursor.close()
            self.close_connection()
            
            # Display success message
            QMessageBox.information(self.main_window, "Success", 
                                   "Student data inserted successfully")
            
            # Clear text boxes
            self.txtStudentID.clear()
            self.txtName.clear()
            self.txtScore.clear()
            
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Error inserting data: {str(e)}")
    
    def tab_changed(self, index):
        #Tab change event
        #When Student Grade tab is clicked, display student grades
        try:
            # Check if Student Grade tab is selected (index 1)
            if index == 1:
                self.display_student_grades()
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Error changing tab: {str(e)}")
    
    def display_student_grades(self):
        #Display student id, name and calculated grade in list widget
        try:
            # Clear list widget
            self.lstStudentData.clear()
            
            # Open database connection
            self.open_connection()
            
            cursor = self.connection.cursor()
            
            # Query to get all student data
            query = "SELECT studentid, studentname, studentscore FROM student_data"
            cursor.execute(query)
            
            # Fetch all rows
            results = cursor.fetchall()
            
            # Iterate over each row and calculate grade
            for row in results:
                student_id = row[0]
                student_name = row[1]
                student_score = row[2]
                
                # Calculate grade based on score
                if student_score >= 90:
                    grade = "A"
                elif student_score >= 80:
                    grade = "B"
                elif student_score >= 70:
                    grade = "C"
                elif student_score >= 60:
                    grade = "D"
                else:
                    grade = "F"
                
                # Add to list widget
                display_text = f"ID: {student_id}, Name: {student_name}, Grade: {grade}"
                self.lstStudentData.addItem(display_text)
            
            cursor.close()
            self.close_connection()
            
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Error displaying grades: {str(e)}")
    
    def export_data(self):
        #Export Data button click event
        #Writes student id, name and grade to external file
        try:
            # Open database connection
            self.open_connection()
            
            cursor = self.connection.cursor()
            
            # Query to get all student data
            query = "SELECT studentid, studentname, studentscore FROM student_data"
            cursor.execute(query)
            
            # Fetch all rows
            results = cursor.fetchall()
            
            # Open file in write mode
            file_object = open("studentgrades.txt", "w")
            
            # Iterate over each row and write to file
            for row in results:
                student_id = row[0]
                student_name = row[1]
                student_score = row[2]
                
                # Calculate grade
                if student_score >= 90:
                    grade = "A"
                elif student_score >= 80:
                    grade = "B"
                elif student_score >= 70:
                    grade = "C"
                elif student_score >= 60:
                    grade = "D"
                else:
                    grade = "F"
                
                # Write to file (each student on new line)
                file_object.write(f"{student_id},{student_name},{grade}\n")
            
            # Close file
            file_object.close()
            
            cursor.close()
            self.close_connection()
            
            # Display success message
            QMessageBox.information(self.main_window, "Success", 
                                   "Student grades exported to studentgrades.txt successfully")
            
        except Exception as e:
            QMessageBox.critical(self.main_window, "Error", f"Error exporting data: {str(e)}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentApp = QtWidgets.QMainWindow()
    ui = Ui_studentApp()
    ui.setupUi(studentApp)
    studentApp.show()
    sys.exit(app.exec())