# Form implementation generated from reading ui file 'firstwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from secondwindow import Ui_secondWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblText = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblText.setGeometry(QtCore.QRect(140, 100, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblText.setFont(font)
        self.lblText.setObjectName("lblText")
        self.txtinput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtinput.setGeometry(QtCore.QRect(270, 100, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtinput.setFont(font)
        self.txtinput.setObjectName("txtinput")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(280, 190, 161, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnDisplay.setFont(font)
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnTransfer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTransfer.setGeometry(QtCore.QRect(300, 260, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnTransfer.setFont(font)
        self.btnTransfer.setObjectName("btnTransfer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.btnDisplay.clicked.connect(self.display_window)
        
        self.btnTransfer.clicked.connect(self.transfer_text)
        
    def transfer_text(self):
        # Get the input text entered by the user in the first window
        input_text = self.txtInput.text()
        # The if statement will check if the object secondui has been created
        if hasattr(self, "secondui"):
        # Setting the input text entered into the first window to the line edit widget in the second window 
            self.secondui.txtTransfereedText.setText(input_text)
        else:
            print("Second window not initalized")
        
    def display_window(self):
        # Create a new window instance
        self.window = QtWidgets.QMainWindow
        # Create an object of the second application window
        self.secondui = Ui_secondWindow()
        self.secondui.setupUi(self.window)
        self.window.show()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblText.setText(_translate("MainWindow", "Enter text"))
        self.btnDisplay.setText(_translate("MainWindow", "Display second window"))
        self.btnTransfer.setText(_translate("MainWindow", "Transfer text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
