# Form implementation generated from reading ui file 'ticketPurchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ticketPurchase(object):
    def setupUi(self, ticketPurchase):
        ticketPurchase.setObjectName("ticketPurchase")
        ticketPurchase.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        ticketPurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=ticketPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.tbMainTab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbMainTab.setGeometry(QtCore.QRect(20, 20, 761, 501))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tbMainTab.setFont(font)
        self.tbMainTab.setObjectName("tbMainTab")
        self.tbTicketPurchase = QtWidgets.QWidget()
        self.tbTicketPurchase.setObjectName("tbTicketPurchase")
        self.lblName = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblName.setGeometry(QtCore.QRect(150, 50, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtName.setGeometry(QtCore.QRect(220, 50, 113, 21))
        self.txtName.setObjectName("txtName")
        self.lblAge = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblAge.setGeometry(QtCore.QRect(150, 90, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblAge.setFont(font)
        self.lblAge.setObjectName("lblAge")
        self.txtAge = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtAge.setGeometry(QtCore.QRect(220, 90, 113, 21))
        self.txtAge.setObjectName("txtAge")
        self.lblTicketType = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblTicketType.setGeometry(QtCore.QRect(150, 150, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblTicketType.setFont(font)
        self.lblTicketType.setObjectName("lblTicketType")
        self.cmbTicketType = QtWidgets.QComboBox(parent=self.tbTicketPurchase)
        self.cmbTicketType.setGeometry(QtCore.QRect(250, 150, 121, 26))
        self.cmbTicketType.setObjectName("cmbTicketType")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.cmbTicketType.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnCalculate.setGeometry(QtCore.QRect(130, 210, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(250, 210, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnPurchase.setFont(font)
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnClear = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnClear.setGeometry(QtCore.QRect(370, 210, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.tbTicketPurchase)
        self.btnExit.setGeometry(QtCore.QRect(490, 210, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        
        self.btnExit.clicked.connect(ticketPurchase.close)
        
        self.lblCost = QtWidgets.QLabel(parent=self.tbTicketPurchase)
        self.lblCost.setGeometry(QtCore.QRect(140, 280, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblCost.setFont(font)
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.tbTicketPurchase)
        self.txtCost.setGeometry(QtCore.QRect(230, 280, 113, 21))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.grpNumberOfTickets = QtWidgets.QGroupBox(parent=self.tbTicketPurchase)
        self.grpNumberOfTickets.setGeometry(QtCore.QRect(390, 129, 141, 61))
        self.grpNumberOfTickets.setObjectName("grpNumberOfTickets")
        self.rd1 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd1.setGeometry(QtCore.QRect(10, 20, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rd1.setFont(font)
        self.rd1.setObjectName("rd1")
        self.rd2 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd2.setGeometry(QtCore.QRect(40, 20, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rd2.setFont(font)
        self.rd2.setObjectName("rd2")
        self.rd3 = QtWidgets.QRadioButton(parent=self.grpNumberOfTickets)
        self.rd3.setGeometry(QtCore.QRect(80, 20, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rd3.setFont(font)
        self.rd3.setObjectName("rd3")
        self.tbMainTab.addTab(self.tbTicketPurchase, "")
        self.tbPurchasesMade = QtWidgets.QWidget()
        self.tbPurchasesMade.setObjectName("tbPurchasesMade")
        self.lstPurchasesMade = QtWidgets.QListWidget(parent=self.tbPurchasesMade)
        self.lstPurchasesMade.setGeometry(QtCore.QRect(60, 80, 651, 341))
        self.lstPurchasesMade.setObjectName("lstPurchasesMade")
        self.lblPurchasesMade = QtWidgets.QLabel(parent=self.tbPurchasesMade)
        self.lblPurchasesMade.setGeometry(QtCore.QRect(70, 60, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblPurchasesMade.setFont(font)
        self.lblPurchasesMade.setObjectName("lblPurchasesMade")
        self.tbMainTab.addTab(self.tbPurchasesMade, "")
        ticketPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ticketPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        ticketPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ticketPurchase)
        self.statusbar.setObjectName("statusbar")
        ticketPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(ticketPurchase)
        self.tbMainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ticketPurchase)
        # Create an empty dictionary to store price dara
        self.price_data = {}
        self.load_data("price.txt")
        
        # Button connecions
        self.btnCalculate.clicked.connect(self.calculate_cost)
        self.btnPurchase.clicked.connect(self.purchase_ticket)
        
        
        
        
        # The even to identify a change in the tab selected
        self.tbMainTab.currentChanged.connect(self.display_data)
        
        self.btnClear.clicked.connect(self.clear) 
        
        self.btnExit.clicked.connect(self.exit_application)
        
    def exit_application(self):
        QtWidgets.QApplication.quit()
        
    def clear(self):  
        #clear the name line edit widget
        self.txtName.clear()
        # clear the age line edit widget 
        self.txtAge.clear()
        # set the ticket type selection to Toplevel
        self.cmbTicketType.setCurrentIndex(0)
        # set the radio button selection to rd1
        self.rd1.setChecked(True)
        # clear the cost line edit widget
        self.txtCost.clear()
    
    def display_data(self):
        # identify which tab the user has clicked. index == 1 indicates the purchases made tab
        try:
            if(self.tbMainTab.currentIndex() == 1):
                # open the file containing the purchases in the read mode, read each line and display the line to a list widget
                with open("Purchases_made.txt", "r") as f:
                    for line in f:
                        self.lstPurchasesMade.addItem(line)
            else:
                # if the user clicks the ticket purchase tab, clear the list widget
                self.lstPurchasesMade.clear()
                
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")
    
    
    def purchase_ticket(self):
        try:
            # get the name entered in the line edit widget
            name = self.txtName.text()
            # get the age entered in the line edit widget
            age = int(self.txtAge.text())
            # get the ticket type selected in the combo box
            current_selection = self.cmbTicketType.currentText()
            # get the radio button clicked
            if(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else: 
                number_of_tickets = 1
            # open the file in the append mode and write the name, age, ticket type, and number of tickets
            with open ("Purchases_made.txt", "a") as f:
                f.write(f" {name}   {age}   {current_selection} {number_of_tickets} \n")
            
            # Add a message box to display save operation was successful 
                        
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            print("Closing any open DB connections")            
     
           
        
    def calculate_cost(self):
        try:
            # get the current ticket selection from the combo box
            current_selection = self.cmbTicketType.currentText()
            # get the radio button clicked by the user
            if(self.rd2.isChecked()):
                number_of_tickets = 2
            elif(self.rd3.isChecked()):
                number_of_tickets = 3
            else: 
                number_of_tickets = 1
            
            # get price of ticket type from dictionary
            price = self.price_data.get(current_selection)
            # calculate the cost of the transaction
            cost = price * number_of_tickets
            # display the cost using the line edit widget
            self.txtCost.setText(f"${cost:.2f}")
        except:
            print("There was an unexpected error")
        finally:
            print("Closing any open DB connections")
                                
        
    def load_data(self, filename):
        try: 
            with open (filename, "r") as f:
                for line in f:
                    #data is a list that will contain the ticket type as the first item and price as the second item after split 
                    data = line.split(",")
                    self.price_data[data[0]] = int(data[1])
                    
        except FileNotFoundError:
            print("The file could not be opened")
        except:
            print("There was an unexpected error")
        finally:
            print("Closing any open DB connections")
            
    
    

    def retranslateUi(self, ticketPurchase):
        _translate = QtCore.QCoreApplication.translate
        ticketPurchase.setWindowTitle(_translate("ticketPurchase", "Ticket Purchase"))
        self.lblName.setText(_translate("ticketPurchase", "Enter Name"))
        self.lblAge.setText(_translate("ticketPurchase", "Enter Age"))
        self.lblTicketType.setText(_translate("ticketPurchase", "Select ticket type"))
        self.cmbTicketType.setItemText(0, _translate("ticketPurchase", "Toplevel"))
        self.cmbTicketType.setItemText(1, _translate("ticketPurchase", "Midlevel"))
        self.cmbTicketType.setItemText(2, _translate("ticketPurchase", "Courtside"))
        self.btnCalculate.setText(_translate("ticketPurchase", "Calculate"))
        self.btnPurchase.setText(_translate("ticketPurchase", "Purchase"))
        self.btnClear.setText(_translate("ticketPurchase", "Clear"))
        self.btnExit.setText(_translate("ticketPurchase", "Exit"))
        self.lblCost.setText(_translate("ticketPurchase", "Cost of purchase"))
        self.grpNumberOfTickets.setTitle(_translate("ticketPurchase", "Number of tickets"))
        self.rd1.setText(_translate("ticketPurchase", "1"))
        self.rd2.setText(_translate("ticketPurchase", "2"))
        self.rd3.setText(_translate("ticketPurchase", "3"))
        self.tbMainTab.setTabText(self.tbMainTab.indexOf(self.tbTicketPurchase), _translate("ticketPurchase", "Ticket Purchase"))
        self.lblPurchasesMade.setText(_translate("ticketPurchase", "Purchases Made"))
        self.tbMainTab.setTabText(self.tbMainTab.indexOf(self.tbPurchasesMade), _translate("ticketPurchase", "Purchases Made"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ticketPurchase = QtWidgets.QMainWindow()
    ui = Ui_ticketPurchase()
    ui.setupUi(ticketPurchase)
    ticketPurchase.show()
    sys.exit(app.exec())
