# Form implementation generated from reading ui file 'studentScores.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
# from QtWidgets import QMessageBox


class Ui_studentScores(object):
    def setupUi(self, studentScores):
        studentScores.setObjectName("studentScores")
        studentScores.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentScores.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentScores)
        self.centralwidget.setObjectName("centralwidget")
        self.lblScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblScore.setGeometry(QtCore.QRect(170, 130, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lblScore.setFont(font)
        self.lblScore.setObjectName("lblScore")
        self.txtScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtScore.setGeometry(QtCore.QRect(300, 130, 113, 21))
        self.txtScore.setObjectName("txtScore")
        self.btnScore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnScore.setGeometry(QtCore.QRect(180, 200, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btnScore.setFont(font)
        self.btnScore.setObjectName("btnScore")
        self.btnAverage = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAverage.setGeometry(QtCore.QRect(310, 200, 151, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btnAverage.setFont(font)
        self.btnAverage.setObjectName("btnAverage")
        self.lstScores = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstScores.setGeometry(QtCore.QRect(480, 80, 256, 192))
        self.lstScores.setObjectName("lstScores")

        self.lblStudentScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentScores.setGeometry(QtCore.QRect(550, 50, 161, 16))
        self.lblStudentScores.setObjectName("lblStudentScores")

        studentScores.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=studentScores)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        studentScores.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=studentScores)
        self.statusbar.setObjectName("statusbar")
        studentScores.setStatusBar(self.statusbar)

        self.retranslateUi(studentScores)
        QtCore.QMetaObject.connectSlotsByName(studentScores)
    
        # Call the add score function when the Add button is clicked
        self.btnScore.clicked.connect(self.add_score)
        
        # Creating an empty list to store all student scores
        self.student_scores_list = []
        
        # Call the calculate_average function when the Average button is clicked 
        self.btnAverage.clicked.connect(self.calculate_average)
        
    def calculate_average(self):
        # Creating an integer object to store the running total
        total = 0
        # Using the len function to count the number of student scores stored in the list
        number_of_items = len(self.student_scores_list)
        msg = QtWidgets.QMessageBox()
        # Modify the title of the message box
        msg.setWindowTitle("Student Scores")
        if(number_of_items > 0):
            for item in self.student_scores_list:
                total = total + item
            
            # Calculate the average
            average_value = total/len(self.student_scores_list)
            
            # Display the average using the message box
            msg.setText(str(average_value))
            
        else:
            msg = QtWidgets.QMessageBox()
            msg.setText("Please enter student scores before calculating the average")
        
        msg.exec()
        
    def add_score(self):
        # Read the student score value entered by the user and transform the value to an integer
        student_score = int(self.txtScore.text())
        # Displau the added score to the list widget
        self.lstScores.addItem(str(student_score))
        # Store/append the student score to the list 
        self.student_scores_list.append(student_score)

    def retranslateUi(self, studentScores):
        _translate = QtCore.QCoreApplication.translate
        studentScores.setWindowTitle(_translate("studentScores", "Student Scores"))
        self.lblScore.setText(_translate("studentScores", "Enter student score"))
        self.btnScore.setText(_translate("studentScores", "Add score"))
        self.btnAverage.setText(_translate("studentScores", "Calculate Average"))
        self.lblStudentScores.setText(_translate("studentScores", "Student Scores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentScores = QtWidgets.QMainWindow()
    ui = Ui_studentScores()
    ui.setupUi(studentScores)
    studentScores.show()
    sys.exit(app.exec())
