# Form implementation generated from reading ui file 'openaidemo.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import openai
api_key = 



class Ui_openAIDemo(object):
    def setupUi(self, openAIDemo):
        openAIDemo.setObjectName("openAIDemo")
        openAIDemo.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        openAIDemo.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=openAIDemo)
        self.centralwidget.setObjectName("centralwidget")
        self.txtInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtInput.setGeometry(QtCore.QRect(170, 70, 391, 21))
        self.txtInput.setObjectName("txtInput")
        self.btnResponse = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnResponse.setGeometry(QtCore.QRect(280, 170, 151, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnResponse.setFont(font)
        self.btnResponse.setObjectName("btnResponse")
        self.lblInput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(330, 30, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblInput.setFont(font)
        self.lblInput.setObjectName("lblInput")
        self.lblResponse = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResponse.setGeometry(QtCore.QRect(310, 260, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblResponse.setFont(font)
        self.lblResponse.setObjectName("lblResponse")
        self.txtResponse = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.txtResponse.setGeometry(QtCore.QRect(200, 320, 321, 181))
        self.txtResponse.setReadOnly(True)
        self.txtResponse.setObjectName("txtResponse")
        openAIDemo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=openAIDemo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        openAIDemo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=openAIDemo)
        self.statusbar.setObjectName("statusbar")
        openAIDemo.setStatusBar(self.statusbar)

        self.retranslateUi(openAIDemo)
        QtCore.QMetaObject.connectSlotsByName(openAIDemo)

    def retranslateUi(self, openAIDemo):
        _translate = QtCore.QCoreApplication.translate
        openAIDemo.setWindowTitle(_translate("openAIDemo", "Open AI Demo"))
        self.btnResponse.setText(_translate("openAIDemo", "Generate Response"))
        self.lblInput.setText(_translate("openAIDemo", "Enter a question"))
        self.lblResponse.setText(_translate("openAIDemo", "Open AI Response"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    openAIDemo = QtWidgets.QMainWindow()
    ui = Ui_openAIDemo()
    ui.setupUi(openAIDemo)
    openAIDemo.show()
    sys.exit(app.exec())
