# Form implementation generated from reading ui file 'fullName.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fullName(object):
    def setupUi(self, fullName):
        fullName.setObjectName("fullName")
        fullName.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("AppleMyungjo")
        font.setPointSize(8)
        fullName.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fullName)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(220, 180, 101, 21))
        self.lblFirstName.setObjectName("lblFirstName")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(330, 180, 113, 21))
        self.txtFirstName.setObjectName("txtFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(220, 220, 101, 16))
        self.lblLastName.setObjectName("lblLastName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(330, 220, 113, 21))
        self.txtLastName.setObjectName("txtLastName")
        self.btnFullName = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFullName.setGeometry(QtCore.QRect(310, 270, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.btnFullName.setFont(font)
        self.btnFullName.setObjectName("btnFullName")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(220, 340, 101, 16))
        self.lblOutput.setObjectName("lblOutput")
        self.txtOutput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtOutput.setGeometry(QtCore.QRect(330, 340, 113, 21))
        self.txtOutput.setReadOnly(True)
        self.txtOutput.setObjectName("txtOutput")
        fullName.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fullName)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        fullName.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fullName)
        self.statusbar.setObjectName("statusbar")
        fullName.setStatusBar(self.statusbar)

        self.retranslateUi(fullName)
        QtCore.QMetaObject.connectSlotsByName(fullName)
        
        self.btnFullName.clicked.connect(self.display_full_name)
        
    def display_full_name(self):
        # Read the value entered by the user in the first name text box and store the value in the python string object first_name
        first_name = self.txtFirstName.text()
        last_name = self.txtLastName.text()
        
        full_name = first_name + " " + last_name
        
        self.txtOutput.setText(full_name)
        
    def retranslateUi(self, fullName):
        _translate = QtCore.QCoreApplication.translate
        fullName.setWindowTitle(_translate("fullName", "Full Name"))
        self.lblFirstName.setText(_translate("fullName", "Enter first name "))
        self.lblLastName.setText(_translate("fullName", "Enter last name"))
        self.btnFullName.setText(_translate("fullName", "Display Full Name"))
        self.lblOutput.setText(_translate("fullName", "Full Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fullName = QtWidgets.QMainWindow()
    ui = Ui_fullName()
    ui.setupUi(fullName)
    fullName.show()
    sys.exit(app.exec())
