# Form implementation generated from reading ui file 'studentData.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_studentData(object):
    def setupUi(self, studentData):
        studentData.setObjectName("studentData")
        studentData.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        studentData.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentData)
        self.centralwidget.setObjectName("centralwidget")
        self.lblId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblId.setGeometry(QtCore.QRect(210, 110, 111, 16))
        self.lblId.setObjectName("lblId")
        self.txtId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtId.setGeometry(QtCore.QRect(350, 110, 113, 21))
        self.txtId.setObjectName("txtId")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(210, 150, 171, 16))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(350, 150, 113, 21))
        self.txtName.setObjectName("txtName")
        self.lblAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAge.setGeometry(QtCore.QRect(210, 190, 171, 16))
        self.lblAge.setObjectName("lblAge")
        self.txtAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAge.setGeometry(QtCore.QRect(350, 190, 113, 21))
        self.txtAge.setObjectName("txtAge")
        self.btnInsert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsert.setGeometry(QtCore.QRect(210, 250, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnInsert.setFont(font)
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(420, 250, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnDisplay.setFont(font)
        self.btnDisplay.setObjectName("btnDisplay")
        self.lstStudentData = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstStudentData.setGeometry(QtCore.QRect(240, 330, 256, 192))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstStudentData.setFont(font)
        self.lstStudentData.setObjectName("lstStudentData")
        self.lblData = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblData.setGeometry(QtCore.QRect(350, 300, 60, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblData.setFont(font)
        self.lblData.setObjectName("lblData")
        studentData.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentData)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        studentData.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentData)
        self.statusbar.setObjectName("statusbar")
        studentData.setStatusBar(self.statusbar)

        self.retranslateUi(studentData)
        QtCore.QMetaObject.connectSlotsByName(studentData)
        
        self.btnInsert.clicked.connect(self.insert)
        
        self.btnDisplay.clicked.connect(self.display_data)
        
    def display_data(self):
        try:
            self.lstStudentData.clear()
            dbconnection = mdb.connect(host="localhost", port=3306, database="student", user="442user", password="442user")
            
            if(dbconnection):
                cursor = dbconnection.cursor()
                cursor.execute("select * from student_data")
                data = cursor.fetchall()
                for item in data:
                    self.lstStudentData.addItem(f"{item[0]}      {item[1]}        {item[2]}")
        except Exception as e:
            print(e)
        finally:
            if(dbconnection):
                dbconnection.close()
        
        
    def insert_data(self):
        try: 
            sid = int(self.txtId.text())
            sname = self.txtName.text()
            sage = int(self.txtAge.text())
            
            dbconnection  mdb.connect(hose="localhost", port=3306, database="student", user="442user", password="442user")
            
            if(dbconnection):
                cursor = dbconnection.cursor()
                cursor.execute("insert into student_data(studentid, studentname, studentage) values (%s, %s, %s)", [sid, sname, sage])
                dbconnection.commit()
                print("Data added")
            else:
                print("DB connection failed")
        except Exception as e:
            print(e)
        finally:
            if(dbconnection):
                dbconnection.close()
            

    def retranslateUi(self, studentData):
        _translate = QtCore.QCoreApplication.translate
        studentData.setWindowTitle(_translate("studentData", "Student Data"))
        self.lblId.setText(_translate("studentData", "Enter student ID"))
        self.lblName.setText(_translate("studentData", "Enter student name"))
        self.lblAge.setText(_translate("studentData", "Enter student age"))
        self.btnInsert.setText(_translate("studentData", "Insert"))
        self.btnDisplay.setText(_translate("studentData", "Display"))
        self.lblData.setText(_translate("studentData", "Student Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentData = QtWidgets.QMainWindow()
    ui = Ui_studentData()
    ui.setupUi(studentData)
    studentData.show()
    sys.exit(app.exec())
