# Form implementation generated from reading ui file 'fruitpurchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fruitPurchase(object):
    def setupUi(self, fruitPurchase):
        fruitPurchase.setObjectName("fruitPurchase")
        fruitPurchase.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        fruitPurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fruitPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(130, 70, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.lblFruit.setFont(font)
        self.lblFruit.setObjectName("lblFruit")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(220, 60, 104, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.cmbFruit.setFont(font)
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(60, 110, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lblQuantity.setFont(font)
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(210, 110, 113, 21))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(220, 170, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.btnCalculate.setFont(font)
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(90, 210, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lblCost.setFont(font)
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(220, 210, 113, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txtCost.setFont(font)
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        fruitPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fruitPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        fruitPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fruitPurchase)
        self.statusbar.setObjectName("statusbar")
        fruitPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(fruitPurchase)
        QtCore.QMetaObject.connectSlotsByName(fruitPurchase)
        
        # Creating a dictionary that stores fruit as keys and price per pound as values
        self.fruit_price_per_pound = {"Apple":3.50, "Orange":3.99, "Mango":4.25, "Kiwi":5.00, "Banana":1.25}
        
        # When the calculate button is clicked, call the calculate_cost function
        self.btnCalculate.clicked.connect(self.calculate_cost)
        
        # The user switching between different options of the combo box. Call the display_price function 
        # when the user selects a fruit from the combo box  
        self.cmbFruit.currentIndexChanged.connect(self.display_price)
        
        self.display_price()
        
        # self.current_fruit = "" - global statement any variable can be accessed
        
    def display_price(self):
        current_fruit = self.cmbFruit.currentText()
        # Validation to check if the current selected value in the combo box is a valid key in the dictionary
        if(current_fruit in self.fruit_price_per_pound.keys()):
            price_per_pound = self.fruit_price_per_pound.get(current_fruit)
            # Display the price with 2 decimal places
            self.lblCost.setText(f"Price per pound: ${price_per_pound:.2f}") 
        
    def calculate_cost(self):
        # Get the crrent selected fruit from the combo box
        current_fruit = self.cmbFruit.currentText()
        number_of_pounds = int(self.txtQuantity.text())
        # Validation to check if the current selected value in the combo box is a valid key in the dictionary
        if(current_fruit in self.fruit_price_per_pound.keys()):
            # Get price per pound from the dictionary using get() method 
            price_per_pound = self.fruit_price_per_pound.get(current_fruit)
        
            cost = number_of_pounds * price_per_pound
            self.txtCost.setText(f"${cost:.2f}")
        else: 
            msg = QtWidgets.QMessageBox()
            msg.setText("Please select a fruit from the dropdown")
            msg.exec()
    

    def retranslateUi(self, fruitPurchase):
        _translate = QtCore.QCoreApplication.translate
        fruitPurchase.setWindowTitle(_translate("fruitPurchase", "Fruit Purchase"))
        self.lblFruit.setText(_translate("fruitPurchase", "Select a fruit"))
        self.cmbFruit.setItemText(0, _translate("fruitPurchase", "Apple"))
        self.cmbFruit.setItemText(1, _translate("fruitPurchase", "Orange"))
        self.cmbFruit.setItemText(2, _translate("fruitPurchase", "Mango"))
        self.cmbFruit.setItemText(3, _translate("fruitPurchase", "Kiwi"))
        self.cmbFruit.setItemText(4, _translate("fruitPurchase", "Banana"))
        self.lblQuantity.setText(_translate("fruitPurchase", "Enter number of pounds"))
        self.btnCalculate.setText(_translate("fruitPurchase", "Calculate Cost"))
        self.lblCost.setText(_translate("fruitPurchase", "Cost of purchase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fruitPurchase = QtWidgets.QMainWindow()
    ui = Ui_fruitPurchase()
    ui.setupUi(fruitPurchase)
    fruitPurchase.show()
    sys.exit(app.exec())
