# Form implementation generated from reading ui file 'evenOrOdd.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_evenOrOdd(object):
    def setupUi(self, evenOrOdd):
        evenOrOdd.setObjectName("evenOrOdd")
        evenOrOdd.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        evenOrOdd.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=evenOrOdd)
        self.centralwidget.setObjectName("centralwidget")
        self.lblNumer = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblNumer.setGeometry(QtCore.QRect(330, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblNumer.setFont(font)
        self.lblNumer.setObjectName("lblNumer")
        self.txtNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtNumber.setGeometry(QtCore.QRect(410, 190, 113, 21))
        self.txtNumber.setObjectName("txtNumber")
        self.btnResult = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnResult.setGeometry(QtCore.QRect(410, 250, 121, 31))
        self.btnResult.setObjectName("btnResult")
        self.lblResult = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblResult.setGeometry(QtCore.QRect(290, 300, 201, 16))
        self.lblResult.setObjectName("lblResult")
        self.txtResult = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtResult.setGeometry(QtCore.QRect(440, 300, 113, 21))
        self.txtResult.setObjectName("txtResult")
        evenOrOdd.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=evenOrOdd)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        evenOrOdd.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=evenOrOdd)
        self.statusbar.setObjectName("statusbar")
        evenOrOdd.setStatusBar(self.statusbar)

        self.retranslateUi(evenOrOdd)
        QtCore.QMetaObject.connectSlotsByName(evenOrOdd)
        
        self.btnResult.clicked.connect(self.even_or_odd)
        
    def even_or_odd(self):
        # Get the current value entered by the user into the text box and store the value into the number object/variable
        number = self.txtNumber.text()
         # We use the int() function to transform the string value to an integer
        integer_number = int(number)
        
        if (integer_number %2 == 0):
            self.txtResult.setText("Even")
        else:
            self.txtResult.setText("Odd")
       
    

    def retranslateUi(self, evenOrOdd):
        _translate = QtCore.QCoreApplication.translate
        evenOrOdd.setWindowTitle(_translate("evenOrOdd", "Even Or Odd"))
        self.lblNumer.setText(_translate("evenOrOdd", "Enter a number"))
        self.btnResult.setText(_translate("evenOrOdd", "Even Or Odd"))
        self.lblResult.setText(_translate("evenOrOdd", "Is number even or odd?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    evenOrOdd = QtWidgets.QMainWindow()
    ui = Ui_evenOrOdd()
    ui.setupUi(evenOrOdd)
    evenOrOdd.show()
    sys.exit(app.exec())
