# Form implementation generated from reading ui file 'gymMembershipCalculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_gymMembershipCalculator(object):
    def setupUi(self, gymMembershipCalculator):
        gymMembershipCalculator.setObjectName("gymMembershipCalculator")
        gymMembershipCalculator.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=gymMembershipCalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.txtFirstName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstName.setGeometry(QtCore.QRect(390, 90, 113, 21))
        self.txtFirstName.setObjectName("txtFirstName")
        self.lblFirstName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstName.setGeometry(QtCore.QRect(240, 90, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblFirstName.setFont(font)
        self.lblFirstName.setObjectName("lblFirstName")
        self.lblLastName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblLastName.setGeometry(QtCore.QRect(240, 120, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblLastName.setFont(font)
        self.lblLastName.setObjectName("lblLastName")
        self.txtLastName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLastName.setGeometry(QtCore.QRect(390, 120, 113, 21))
        self.txtLastName.setObjectName("txtLastName")
        self.lblAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAge.setGeometry(QtCore.QRect(240, 150, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblAge.setFont(font)
        self.lblAge.setObjectName("lblAge")
        self.txtAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAge.setGeometry(QtCore.QRect(390, 150, 113, 21))
        self.txtAge.setObjectName("txtAge")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(240, 200, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblPlan.setFont(font)
        self.lblPlan.setObjectName("lblPlan")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(390, 200, 104, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cmbPlan.setFont(font)
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.ckbStudentDiscount = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.ckbStudentDiscount.setGeometry(QtCore.QRect(300, 250, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.ckbStudentDiscount.setFont(font)
        self.ckbStudentDiscount.setObjectName("ckbStudentDiscount")
        self.btnFee = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnFee.setGeometry(QtCore.QRect(250, 290, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnFee.setFont(font)
        self.btnFee.setObjectName("btnFee")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(390, 290, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(310, 430, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.lblFirstMonthFee = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFirstMonthFee.setGeometry(QtCore.QRect(240, 350, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblFirstMonthFee.setFont(font)
        self.lblFirstMonthFee.setObjectName("lblFirstMonthFee")
        self.txtFirstMonthFee = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtFirstMonthFee.setGeometry(QtCore.QRect(400, 350, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtFirstMonthFee.setFont(font)
        self.txtFirstMonthFee.setReadOnly(True)
        self.txtFirstMonthFee.setObjectName("txtFirstMonthFee")
        self.lblMonthlyFee = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblMonthlyFee.setGeometry(QtCore.QRect(240, 380, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblMonthlyFee.setFont(font)
        self.lblMonthlyFee.setObjectName("lblMonthlyFee")
        self.txtMonthlyFee = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtMonthlyFee.setGeometry(QtCore.QRect(400, 380, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtMonthlyFee.setFont(font)
        self.txtMonthlyFee.setReadOnly(True)
        self.txtMonthlyFee.setObjectName("txtMonthlyFee")
        gymMembershipCalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=gymMembershipCalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        gymMembershipCalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=gymMembershipCalculator)
        self.statusbar.setObjectName("statusbar")
        gymMembershipCalculator.setStatusBar(self.statusbar)

        self.retranslateUi(gymMembershipCalculator)
        
        # Connect button signals to slots
        self.btnFee.clicked.connect(lambda: self.calculate_fee(gymMembershipCalculator))
        self.btnClear.clicked.connect(self.clear_form)
        self.btnExit.clicked.connect(gymMembershipCalculator.close)
        
        QtCore.QMetaObject.connectSlotsByName(gymMembershipCalculator)

    def retranslateUi(self, gymMembershipCalculator):
        _translate = QtCore.QCoreApplication.translate
        gymMembershipCalculator.setWindowTitle(_translate("gymMembershipCalculator", "MainWindow"))
        self.lblFirstName.setText(_translate("gymMembershipCalculator", "Please enter your first name"))
        self.lblLastName.setText(_translate("gymMembershipCalculator", "Please enter your last name"))
        self.lblAge.setText(_translate("gymMembershipCalculator", "Please enter your age"))
        self.lblPlan.setText(_translate("gymMembershipCalculator", "Select your perferred plan"))
        self.cmbPlan.setItemText(0, _translate("gymMembershipCalculator", "Basic"))
        self.cmbPlan.setItemText(1, _translate("gymMembershipCalculator", "Standard"))
        self.cmbPlan.setItemText(2, _translate("gymMembershipCalculator", "Premium"))
        self.cmbPlan.setItemText(3, _translate("gymMembershipCalculator", "Family"))
        self.ckbStudentDiscount.setText(_translate("gymMembershipCalculator", "Student discount (20%)"))
        self.btnFee.setText(_translate("gymMembershipCalculator", "Calculate Fee"))
        self.btnClear.setText(_translate("gymMembershipCalculator", "Clear Form"))
        self.btnExit.setText(_translate("gymMembershipCalculator", "Exit"))
        self.lblFirstMonthFee.setText(_translate("gymMembershipCalculator", "First Month Fee"))
        self.lblMonthlyFee.setText(_translate("gymMembershipCalculator", "Monthly Fee After First Month"))
        
    def calculate_fee(self, gymMembershipCalculator):
        # Validate that all fields are filled
        if(self.txtFirstName.text() == ""):
            QMessageBox.warning(gymMembershipCalculator, "Input Error", "Please enter your first name")
            return
        
        if(self.txtLastName.text() == ""):
            QMessageBox.warning(gymMembershipCalculator, "Input Error", "Please enter your last name")
            return
        
        if(self.txtAge.text() == ""):
            QMessageBox.warning(gymMembershipCalculator, "Input Error", "Please enter your age")
            return
        
        # Get the selected plan
        selected_plan = self.cmbPlan.currentText()
        
        # Dictionary to store base monthly fees
        plan_fees = {"Basic": 30, "Standard": 45, "Premium": 60, "Family": 80}
        
        # Get base fee for selected plan
        base_fee = plan_fees[selected_plan]
        
        # Facility fee (one-time)
        facility_fee = 20
        
        # Calculate discount if student checkbox is checked
        discount = 0
        if(self.ckbStudentDiscount.isChecked()):
            discount = base_fee * 0.20
        
        # Calculate first month fee (base fee - discount + facility fee)
        first_month_fee = base_fee - discount + facility_fee
        
        # Calculate monthly fee after first month (base fee - discount)
        monthly_fee = base_fee - discount
        
        # Display the results
        self.txtFirstMonthFee.setText("$" + str(first_month_fee))
        self.txtMonthlyFee.setText("$" + str(monthly_fee))
    
    def clear_form(self):
        # Clear all text boxes
        self.txtFirstName.clear()
        self.txtLastName.clear()
        self.txtAge.clear()
        
        # Reset combo box to first option
        self.cmbPlan.setCurrentIndex(0)
        
        # Uncheck the student discount checkbox
        self.ckbStudentDiscount.setChecked(False)
        
        # Clear output fields
        self.txtFirstMonthFee.clear()
        self.txtMonthlyFee.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    gymMembershipCalculator = QtWidgets.QMainWindow()
    ui = Ui_gymMembershipCalculator()
    ui.setupUi(gymMembershipCalculator)
    gymMembershipCalculator.show()
    sys.exit(app.exec())
