# Form implementation generated from reading ui file 'dbTest.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mbd

class Ui_dbTest(object):
    def setupUi(self, dbTest):
        dbTest.setObjectName("dbTest")
        dbTest.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        dbTest.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=dbTest)
        self.centralwidget.setObjectName("centralwidget")
        self.btnTest = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTest.setGeometry(QtCore.QRect(320, 190, 113, 32))
        self.btnTest.setObjectName("btnTest")
        dbTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dbTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        dbTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dbTest)
        self.statusbar.setObjectName("statusbar")
        dbTest.setStatusBar(self.statusbar)

        self.retranslateUi(dbTest)
        QtCore.QMetaObject.connectSlotsByName(dbTest)
        
    def db_connect(self):
        try:
            connection_object = mbd.connect(host="localhost", port=3306, database="student", user="442user", password="442user")
            if (connection_object):
                msg = Qtwidgets.QMessageBox()
                msg.setText("DB Connection Successful")
            else: 
                print("DB Connection failed")
        except Exception as e: 
            print(e)
        finally:
            if(connection_object):
                connection_

    def retranslateUi(self, dbTest):
        _translate = QtCore.QCoreApplication.translate
        dbTest.setWindowTitle(_translate("dbTest", "DB Test"))
        self.btnTest.setText(_translate("dbTest", "Test DB Connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dbTest = QtWidgets.QMainWindow()
    ui = Ui_dbTest()
    ui.setupUi(dbTest)
    dbTest.show()
    sys.exit(app.exec())
