# Form implementation generated from reading ui file 'financialPlanner.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner(object):
    def setupUi(self, financialPlanner):
        financialPlanner.setObjectName("financialPlanner")
        financialPlanner.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        financialPlanner.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner)
        self.centralwidget.setObjectName("centralwidget")
        self.lblDeposit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblDeposit.setGeometry(QtCore.QRect(130, 80, 261, 21))
        self.lblDeposit.setObjectName("lblDeposit")
        self.txtDeposit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtDeposit.setGeometry(QtCore.QRect(320, 80, 113, 21))
        self.txtDeposit.setObjectName("txtDeposit")
        self.lblTarget = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTarget.setGeometry(QtCore.QRect(130, 110, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lblTarget.setFont(font)
        self.lblTarget.setObjectName("lblTarget")
        self.txtTarget = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTarget.setGeometry(QtCore.QRect(320, 110, 113, 21))
        self.txtTarget.setObjectName("txtTarget")
        self.lblPlan = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPlan.setGeometry(QtCore.QRect(130, 150, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lblPlan.setFont(font)
        self.lblPlan.setObjectName("lblPlan")
        self.cmbPlan = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbPlan.setGeometry(QtCore.QRect(270, 140, 151, 26))
        self.cmbPlan.setEditable(False)
        self.cmbPlan.setObjectName("cmbPlan")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.cmbPlan.addItem("")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(300, 180, 113, 32))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(150, 300, 121, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(270, 300, 113, 21))
        self.txtTime.setReadOnly(True)
        self.txtTime.setObjectName("txtTime")
        financialPlanner.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        financialPlanner.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner)
        self.statusbar.setObjectName("statusbar")
        financialPlanner.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner)
        
        self.btnCalculate.clicked.connect()
    
    def calculate_time(self):
        # Read the user input entereed in the deposit line edit widget and transform the value to an integer
        annumal_amount = int(self.txtDeposit.text())
        taregt_amount = int(self.textTarget.text())
        # Identify the currently selected retirement plan from the combo box
        retirement_plan = self.cmbPlan.currentText()
        
        if(retirement_plan == "Plan 2040"):
            rate = 7.0
        elif(retirement_plan == "Plan 2050"):
            rate = 6.0
        else:
            rate = 5.0
            
        current_portfolio_amount = 0
        time_taken = 0
        
    while(current_portfolio_amount < target_amount):
        current_portfolio_amount = (current_portfolio_amount + annual_amount) * (1 + rate/100)
        time_taken = time_taken + 1

    def retranslateUi(self, financialPlanner):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner.setWindowTitle(_translate("financialPlanner", "Financial Planner"))
        self.lblDeposit.setText(_translate("financialPlanner", "Enter annual deposit amount"))
        self.lblTarget.setText(_translate("financialPlanner", "Enter target portfolio amount"))
        self.lblPlan.setText(_translate("financialPlanner", "Select retirement plan"))
        self.cmbPlan.setItemText(0, _translate("financialPlanner", "Plan 2040"))
        self.cmbPlan.setItemText(1, _translate("financialPlanner", "Plan 2050"))
        self.cmbPlan.setItemText(2, _translate("financialPlanner", "Plan 2060"))
        self.btnCalculate.setText(_translate("financialPlanner", "Calculate"))
        self.lblTime.setText(_translate("financialPlanner", "Number of years"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner()
    ui.setupUi(financialPlanner)
    financialPlanner.show()
    sys.exit(app.exec())
