# Form implementation generated from reading ui file 'homePurchase.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_homePurchase(object):
    def setupUi(self, homePurchase):
        homePurchase.setObjectName("homePurchase")
        homePurchase.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        homePurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=homePurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.tbMainTab = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbMainTab.setGeometry(QtCore.QRect(40, 10, 731, 501))
        self.tbMainTab.setObjectName("tbMainTab")
        self.tbHomePurchase = QtWidgets.QWidget()
        self.tbHomePurchase.setObjectName("tbHomePurchase")
        self.txtCustomerName = QtWidgets.QLineEdit(parent=self.tbHomePurchase)
        self.txtCustomerName.setGeometry(QtCore.QRect(210, 60, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCustomerName.setFont(font)
        self.txtCustomerName.setObjectName("txtCustomerName")
        self.lblCustomerName = QtWidgets.QLabel(parent=self.tbHomePurchase)
        self.lblCustomerName.setGeometry(QtCore.QRect(90, 60, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblCustomerName.setFont(font)
        self.lblCustomerName.setObjectName("lblCustomerName")
        self.lblCustomerAge = QtWidgets.QLabel(parent=self.tbHomePurchase)
        self.lblCustomerAge.setGeometry(QtCore.QRect(90, 90, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblCustomerAge.setFont(font)
        self.lblCustomerAge.setObjectName("lblCustomerAge")
        self.txtCustomerAge = QtWidgets.QLineEdit(parent=self.tbHomePurchase)
        self.txtCustomerAge.setGeometry(QtCore.QRect(210, 90, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtCustomerAge.setFont(font)
        self.txtCustomerAge.setObjectName("txtCustomerAge")
        self.cmbHouseSelection = QtWidgets.QComboBox(parent=self.tbHomePurchase)
        self.cmbHouseSelection.setGeometry(QtCore.QRect(220, 140, 104, 26))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.cmbHouseSelection.setFont(font)
        self.cmbHouseSelection.setObjectName("cmbHouseSelection")
        self.cmbHouseSelection.addItem("")
        self.cmbHouseSelection.addItem("")
        self.cmbHouseSelection.addItem("")
        self.cmbHouseSelection.addItem("")
        self.lblHouseSelection = QtWidgets.QLabel(parent=self.tbHomePurchase)
        self.lblHouseSelection.setGeometry(QtCore.QRect(60, 140, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblHouseSelection.setFont(font)
        self.lblHouseSelection.setObjectName("lblHouseSelection")
        self.grbModelType = QtWidgets.QGroupBox(parent=self.tbHomePurchase)
        self.grbModelType.setGeometry(QtCore.QRect(70, 190, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.grbModelType.setFont(font)
        self.grbModelType.setObjectName("grbModelType")
        self.rdStandard = QtWidgets.QRadioButton(parent=self.grbModelType)
        self.rdStandard.setGeometry(QtCore.QRect(10, 20, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rdStandard.setFont(font)
        self.rdStandard.setObjectName("rdStandard")
        self.rdSmart = QtWidgets.QRadioButton(parent=self.grbModelType)
        self.rdSmart.setGeometry(QtCore.QRect(10, 40, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rdSmart.setFont(font)
        self.rdSmart.setObjectName("rdSmart")
        self.rdLuxury = QtWidgets.QRadioButton(parent=self.grbModelType)
        self.rdLuxury.setGeometry(QtCore.QRect(10, 60, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.rdLuxury.setFont(font)
        self.rdLuxury.setObjectName("rdLuxury")
        self.lblInitialDownPayment = QtWidgets.QLabel(parent=self.tbHomePurchase)
        self.lblInitialDownPayment.setGeometry(QtCore.QRect(20, 310, 221, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblInitialDownPayment.setFont(font)
        self.lblInitialDownPayment.setObjectName("lblInitialDownPayment")
        self.txtInitialDownPayment = QtWidgets.QLineEdit(parent=self.tbHomePurchase)
        self.txtInitialDownPayment.setGeometry(QtCore.QRect(240, 310, 113, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.txtInitialDownPayment.setFont(font)
        self.txtInitialDownPayment.setObjectName("txtInitialDownPayment")
        self.lstMonthlyPayments = QtWidgets.QListWidget(parent=self.tbHomePurchase)
        self.lstMonthlyPayments.setGeometry(QtCore.QRect(390, 270, 251, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lstMonthlyPayments.setFont(font)
        self.lstMonthlyPayments.setObjectName("lstMonthlyPayments")
        self.lblMonthlyPayments = QtWidgets.QLabel(parent=self.tbHomePurchase)
        self.lblMonthlyPayments.setGeometry(QtCore.QRect(470, 250, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblMonthlyPayments.setFont(font)
        self.lblMonthlyPayments.setObjectName("lblMonthlyPayments")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.tbHomePurchase)
        self.btnPurchase.setGeometry(QtCore.QRect(130, 430, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnPurchase.setFont(font)
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnShowPayments = QtWidgets.QPushButton(parent=self.tbHomePurchase)
        self.btnShowPayments.setGeometry(QtCore.QRect(250, 430, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnShowPayments.setFont(font)
        self.btnShowPayments.setObjectName("btnShowPayments")
        self.btnExit = QtWidgets.QPushButton(parent=self.tbHomePurchase)
        self.btnExit.setGeometry(QtCore.QRect(370, 430, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.btnClear = QtWidgets.QPushButton(parent=self.tbHomePurchase)
        self.btnClear.setGeometry(QtCore.QRect(490, 430, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.btnClear.setFont(font)
        self.btnClear.setObjectName("btnClear")
        self.tbMainTab.addTab(self.tbHomePurchase, "")
        self.tbPurchasesMade = QtWidgets.QWidget()
        self.tbPurchasesMade.setObjectName("tbPurchasesMade")
        self.lstPastHomePurchases = QtWidgets.QListWidget(parent=self.tbPurchasesMade)
        self.lstPastHomePurchases.setGeometry(QtCore.QRect(240, 110, 256, 192))
        self.lstPastHomePurchases.setObjectName("lstPastHomePurchases")
        self.lblPastHomePurchases = QtWidgets.QLabel(parent=self.tbPurchasesMade)
        self.lblPastHomePurchases.setGeometry(QtCore.QRect(320, 80, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lblPastHomePurchases.setFont(font)
        self.lblPastHomePurchases.setObjectName("lblPastHomePurchases")
        self.tbMainTab.addTab(self.tbPurchasesMade, "")
        homePurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=homePurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        homePurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=homePurchase)
        self.statusbar.setObjectName("statusbar")
        homePurchase.setStatusBar(self.statusbar)

        self.retranslateUi(homePurchase)
        self.tbMainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(homePurchase)
        
        # Store reference to main window 
        self.main_window = homePurchase
        
        # Dictionary to store house prices 
        self.house_prices = {}
        
        # Load house prices from file when application starts 
        self.load_house_prices()
        
        # Connect buttons to their functions 
        self.btnPurchase.clicked.connect(self.purchase_home)
        self.btnShowPayments.clicked.connect(self.show_payments)
        self.btnExit.clicked.connect(self.exit_application)
        self.btnClear.clicked.connect(self.clear_fields)
        
        # Connect tab change event 
        self.tbMainTab.currentChanged.connect(self.tab_changed)

    def retranslateUi(self, homePurchase):
        _translate = QtCore.QCoreApplication.translate
        homePurchase.setWindowTitle(_translate("homePurchase", "Home Purchase"))
        self.lblCustomerName.setText(_translate("homePurchase", "Please enter your name"))
        self.lblCustomerAge.setText(_translate("homePurchase", "Please enter your age"))
        self.cmbHouseSelection.setItemText(0, _translate("homePurchase", "Apartment"))
        self.cmbHouseSelection.setItemText(1, _translate("homePurchase", "Townhouse"))
        self.cmbHouseSelection.setItemText(2, _translate("homePurchase", "Single-Family Home"))
        self.cmbHouseSelection.setItemText(3, _translate("homePurchase", "Luxury Villa"))
        self.lblHouseSelection.setText(_translate("homePurchase", "Please select your house type"))
        self.grbModelType.setTitle(_translate("homePurchase", "Select your model type"))
        self.rdStandard.setText(_translate("homePurchase", "Standard"))
        self.rdSmart.setText(_translate("homePurchase", "Smart"))
        self.rdLuxury.setText(_translate("homePurchase", "Luxury"))
        self.lblInitialDownPayment.setText(_translate("homePurchase", "Please enter your initial down payment amount"))
        self.lblMonthlyPayments.setText(_translate("homePurchase", "Monthly Payments"))
        self.btnPurchase.setText(_translate("homePurchase", "Purchase"))
        self.btnShowPayments.setText(_translate("homePurchase", "Show payments"))
        self.btnExit.setText(_translate("homePurchase", "Exit"))
        self.btnClear.setText(_translate("homePurchase", "Clear"))
        self.tbMainTab.setTabText(self.tbMainTab.indexOf(self.tbHomePurchase), _translate("homePurchase", "Home Purchase"))
        self.lblPastHomePurchases.setText(_translate("homePurchase", "Past Home Purchases"))
        self.tbMainTab.setTabText(self.tbMainTab.indexOf(self.tbPurchasesMade), _translate("homePurchase", "Purchases Made"))

    # Function to load house prices from file 
    def load_house_prices(self):
        """Load house prices from external file and store in dictionary"""
        try:
            # Open the file in read mode
            file = open("houseprice.txt", "r")
            
            # Read all lines from the file
            lines = file.readlines()
            
            # Process each line and add to dictionary
            for line in lines:
                # Remove whitespace and split by colon
                line = line.strip()
                if ":" in line:
                    parts = line.split(":")
                    house_type = parts[0].strip()
                    price = float(parts[1].strip())
                    self.house_prices[house_type] = price
                elif "," in line:
                    # Handle comma-separated format
                    parts = line.split(",")
                    house_type = parts[0].strip()
                    price = float(parts[1].strip())
                    self.house_prices[house_type] = price
            
            # Close the file
            file.close()
            
        except FileNotFoundError:
            # Display error message if file cannot be found
            QMessageBox.critical(self.main_window, "Error", "houseprice.txt file not found. Please ensure it is in the same directory as this program.")
        except:
            # Display error message if file cannot be read
            QMessageBox.critical(self.main_window, "Error", "Could not load house prices from houseprice.txt. Please check the file format.")
    
    # Function to handle Purchase button click 
    def purchase_home(self):
        """Validate inputs and save purchase to file"""
        # Get all input values
        customer_name = self.txtCustomerName.text()
        customer_age = self.txtCustomerAge.text()
        house_type = self.cmbHouseSelection.currentText()
        down_payment = self.txtInitialDownPayment.text()
        
        # Check which radio button is selected
        model_type = ""
        if self.rdStandard.isChecked():
            model_type = "Standard"
        elif self.rdSmart.isChecked():
            model_type = "Smart"
        elif self.rdLuxury.isChecked():
            model_type = "Luxury"
        
        # Validate all fields are filled
        if customer_name == "":
            QMessageBox.warning(self.main_window, "Validation Error", "Please enter customer name")
            return
        
        if customer_age == "":
            QMessageBox.warning(self.main_window, "Validation Error", "Please enter customer age")
            return
        
        if model_type == "":
            QMessageBox.warning(self.main_window, "Validation Error", "Please select a model type")
            return
        
        if down_payment == "":
            QMessageBox.warning(self.main_window, "Validation Error", "Please enter down payment amount")
            return
        
        # Write data to external file
        try:
            # Open file in append mode
            file = open("purchases_made.txt", "a")
            
            # Write purchase information
            file.write(f"{customer_name},{customer_age},{house_type},{model_type},{down_payment}\n")
            
            # Close the file
            file.close()
            
            # Display success message
            QMessageBox.information(self.main_window, "Success", "Home purchase recorded successfully!")
            
        except:
            QMessageBox.critical(self.main_window, "Error", "Could not save purchase information")
    
    # Function to calculate and show monthly payments
    def show_payments(self):
        """Calculate and display monthly payments"""
        # Clear the list widget first
        self.lstMonthlyPayments.clear()
        
        # Get all input values
        house_type = self.cmbHouseSelection.currentText()
        down_payment_text = self.txtInitialDownPayment.text()
        
        # Check which radio button is selected
        model_type = ""
        if self.rdStandard.isChecked():
            model_type = "Standard"
        elif self.rdSmart.isChecked():
            model_type = "Smart"
        elif self.rdLuxury.isChecked():
            model_type = "Luxury"
        
        # Validate inputs
        if model_type == "":
            QMessageBox.warning(self.main_window, "Validation Error", "Please select a model type")
            return
        
        if down_payment_text == "":
            QMessageBox.warning(self.main_window, "Validation Error", "Please enter down payment amount")
            return
        
        try:
            # Get house price from dictionary
            house_price = self.house_prices[house_type]
            
            # Modify price based on model type
            if model_type == "Smart":
                house_price = house_price + (house_price * 0.15)
            elif model_type == "Luxury":
                house_price = house_price + (house_price * 0.20)
            # Standard model has no price modification
            
            # Convert down payment to float
            down_payment = float(down_payment_text)
            
            # Calculate loan amount
            loan_amount = house_price - down_payment
            
            # Validate loan amount is positive
            if loan_amount <= 0:
                QMessageBox.warning(self.main_window, "Validation Error", "Down payment cannot be greater than or equal to house price")
                return
            
            # Set interest rate and loan term
            annual_interest_rate = 0.07
            loan_term_months = 120
            
            # Calculate monthly interest rate
            monthly_rate = annual_interest_rate / 12
            
            # Calculate fixed monthly payment using the formula
            monthly_payment = loan_amount * monthly_rate * (1 + monthly_rate) ** loan_term_months / ((1 + monthly_rate) ** loan_term_months - 1)
            
            # Display header in list widget
            self.lstMonthlyPayments.addItem("Month\t\tPayment\t\tRemaining Balance")
            self.lstMonthlyPayments.addItem("-" * 60)
            
            # Iterate month-by-month reducing the balance until it reaches zero
            remaining_balance = loan_amount
            month = 1
            
            while remaining_balance > 0:
                # Calculate interest for this month
                interest_payment = remaining_balance * monthly_rate
                
                # Calculate principal payment
                principal_payment = monthly_payment - interest_payment
                
                # Update remaining balance
                remaining_balance = remaining_balance - principal_payment
                
                # Make sure balance doesn't go negative
                if remaining_balance < 0:
                    remaining_balance = 0
                
                # Display month information with three columns
                payment_info = f"{month}\t\t${monthly_payment:.2f}\t\t${remaining_balance:.2f}"
                self.lstMonthlyPayments.addItem(payment_info)
                
                # Increment month
                month = month + 1
                
        except KeyError:
            QMessageBox.critical(self.main_window, "Error", "House price not found. Please ensure houseprice.txt is loaded correctly.")
        except ValueError:
            QMessageBox.critical(self.main_window, "Error", "Invalid down payment amount. Please enter a valid number.")
        except:
            QMessageBox.critical(self.main_window, "Error", "Error calculating payments. Please check your inputs.")
    
    # Function to clear all input fields 
    def clear_fields(self):
        """Clear all input fields"""
        # Clear text boxes
        self.txtCustomerName.clear()
        self.txtCustomerAge.clear()
        self.txtInitialDownPayment.clear()
        
        # Reset combo box to first item
        self.cmbHouseSelection.setCurrentIndex(0)
        
        # Uncheck all radio buttons
        self.rdStandard.setChecked(False)
        self.rdSmart.setChecked(False)
        self.rdLuxury.setChecked(False)
        
        # Clear list widget
        self.lstMonthlyPayments.clear()
    
    # Function to exit the application
    def exit_application(self):
        """Exit the application"""
        self.main_window.close()
    
    # Function to handle tab change event
    def tab_changed(self):
        """Event handler when tab is changed"""
        # Check if Purchases Made tab is selected
        if self.tbMainTab.currentIndex() == 1:
            # Clear the list widget
            self.lstPastHomePurchases.clear()
            
            # Read data from purchases_made.txt file
            try:
                # Open file in read mode
                file = open("purchases_made.txt", "r")
                
                # Read all lines
                lines = file.readlines()
                
                # Display each line in the list widget
                for line in lines:
                    line = line.strip()
                    self.lstPastHomePurchases.addItem(line)
                
                # Close the file
                file.close()
                
            except:
                # If file doesn't exist, display message
                self.lstPastHomePurchases.addItem("No purchases made yet")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homePurchase = QtWidgets.QMainWindow()
    ui = Ui_homePurchase()
    ui.setupUi(homePurchase)
    homePurchase.show()
    sys.exit(app.exec())