# Form implementation generated from reading ui file 'financialPlanner2.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_financialPlanner2(object):
    def setupUi(self, financialPlanner2):
        financialPlanner2.setObjectName("financialPlanner2")
        financialPlanner2.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        financialPlanner2.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=financialPlanner2)
        self.centralwidget.setObjectName("centralwidget")
        self.lblAmount = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblAmount.setGeometry(QtCore.QRect(110, 110, 241, 16))
        self.lblAmount.setObjectName("lblAmount")
        self.lblTime = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTime.setGeometry(QtCore.QRect(110, 160, 181, 16))
        self.lblTime.setObjectName("lblTime")
        self.txtAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAmount.setGeometry(QtCore.QRect(320, 110, 113, 21))
        self.txtAmount.setObjectName("txtAmount")
        self.txtTime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtTime.setGeometry(QtCore.QRect(320, 160, 113, 21))
        self.txtTime.setObjectName("txtTime")
        self.chkRate = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.chkRate.setGeometry(QtCore.QRect(320, 230, 87, 20))
        self.chkRate.setObjectName("chkRate")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(120, 320, 113, 32))
        self.btnCalculate.setObjectName("btnCalculate")
        self.btnClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClear.setGeometry(QtCore.QRect(250, 320, 113, 32))
        self.btnClear.setObjectName("btnClear")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(370, 320, 113, 32))
        self.btnExit.setObjectName("btnExit")
        self.lstOuput = QtWidgets.QListView(parent=self.centralwidget)
        self.lstOuput.setGeometry(QtCore.QRect(510, 80, 256, 291))
        self.lstOuput.setObjectName("lstOuput")
        self.lblOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(510, 40, 261, 16))
        self.lblOutput.setObjectName("lblOutput")
        financialPlanner2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=financialPlanner2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        financialPlanner2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=financialPlanner2)
        self.statusbar.setObjectName("statusbar")
        financialPlanner2.setStatusBar(self.statusbar)

        self.retranslateUi(financialPlanner2)
        QtCore.QMetaObject.connectSlotsByName(financialPlanner2)
        
        self.btnCalculate.clicked.connect(self.calculate_portfolio_balance)
        
    def calculate_portfolio_balance(self):
        annual_amount = int(self.txtAmount.text())
        number_of_years = int(self.txtTime.text())
        
        if(self.chkRate.isChecked):
            rate = 7.0
        else:
            rate = 5.0
            
        initial_amount = 0 
        for time in range(1, number_of_years + 1):
            initial_amount = (initial_amount + annual_amount) * (1 + rate/100)
            self.lstOutput.addItem(str(time)+ " " + str(initial_amount))
        

    def retranslateUi(self, financialPlanner2):
        _translate = QtCore.QCoreApplication.translate
        financialPlanner2.setWindowTitle(_translate("financialPlanner2", "Financial Planner 2"))
        self.lblAmount.setText(_translate("financialPlanner2", "Enter annual deposit amount"))
        self.lblTime.setText(_translate("financialPlanner2", "Number of years to invest"))
        self.chkRate.setText(_translate("financialPlanner2", "High Risk"))
        self.btnCalculate.setText(_translate("financialPlanner2", "Calculate "))
        self.btnClear.setText(_translate("financialPlanner2", "Clear"))
        self.btnExit.setText(_translate("financialPlanner2", "Exit"))
        self.lblOutput.setText(_translate("financialPlanner2", "Portfolio balanceamount after each year"))
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    financialPlanner2 = QtWidgets.QMainWindow()
    ui = Ui_financialPlanner2()
    ui.setupUi(financialPlanner2)
    financialPlanner2.show()
    sys.exit(app.exec())
